type Comment {
  id: ID!
  body: String!
  username: String!
  createdAt: String
}

type Mutation {
  createComment(postId: ID!, body: String!): Post
  deleteComment(postId: ID!, commentId: ID!): Post
}
