type User {
  id: ID!
  username: String!
  email: String!
  token: String!
  createdAt: String!
}

input UserInput {
  username: String!
  email: String!
  password: String!
  confirmPassword: String!
}

type Mutation {
  createUser(data: UserInput): User!
  login(username: String!, password: String!): User!
}
